//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Photocom.Models.Entities.Database;
using Photocom.Models.Entities.Database;

namespace Photocom.Models.Entities.Database
{
    public class Photo : BaseEntity
    {
        public virtual void Like()
        {
            throw new System.NotImplementedException();
        }

        public virtual IList<Comment> Comments { get; set; }

        public virtual IList<string> HashTags { get; set; }

        public virtual string Description { get; set; }

        public virtual IList<User> Likes { get; set; }

        public virtual Category Category { get; set; }

        public virtual User Author { get; set; }


        public DateTime PublicationDate { get; set; }

    }
}

