//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Photocom.Models.Entities.Database;

namespace Photocom.Models.Entities.Database
{
    public class User : BaseEntity
    {
        public virtual string FirstName { get; set; }

        public virtual string LastName { get; set; }

        public virtual string Email { get; set; }

        public virtual string Password { get; set; }

        public virtual string AboutUser { get; set; }

        public virtual Guid GUID { get; set; }

        public virtual string Login { get; set; }

        public virtual DateTime SignUpDate { get; set; }

        public override bool Equals(object obj)
        {
            User other = obj as User;

            return other != null && other.Login.Equals(this.Login);
        }

        public string GetFullName()
        {
            return $"{FirstName} {LastName}";
        }

    }
}

