//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Photocom.Models.Entities;

namespace Photocom.Models.Entities
{
    public class Privilege
    {
        public virtual IEnumerable<Permission> Permissions { get; set; }

    }
}
