//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Photo
{
	public virtual object Comments
	{
		get;
		set;
	}

	public virtual object HashTags
	{
		get;
		set;
	}

	public virtual object Description
	{
		get;
		set;
	}

	public virtual object Likes
	{
		get;
		set;
	}

	public virtual void Like()
	{
		throw new System.NotImplementedException();
	}

}

