//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	public virtual object FirstName
	{
		get;
		set;
	}

	public virtual object LastName
	{
		get;
		set;
	}

	public virtual object Email
	{
		get;
		set;
	}

	public virtual object Password
	{
		get;
		set;
	}

	public virtual object AboutUser
	{
		get;
		set;
	}

	public virtual object GUID
	{
		get;
		set;
	}

	public virtual object Login
	{
		get;
		set;
	}

}

