//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Photocom.BusinessLogic.Controllers
{
    public class AuthController
    {
        public virtual void Login()
        {
            throw new System.NotImplementedException();
        }

        public virtual void Logout()
        {
            throw new System.NotImplementedException();
        }

        public virtual void GetCurrentSession()
        {
            throw new System.NotImplementedException();
        }

        public virtual void GetCurrentUser()
        {
            throw new System.NotImplementedException();
        }

    }
}

