//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Photocom.BusinessLogic.Controllers
{
    public class PhotosController
    {
        public virtual void GetLastPhotos()
        {
            throw new System.NotImplementedException();
        }

        public virtual void Find()
        {
            throw new System.NotImplementedException();
        }

        public virtual void Filter()
        {
            throw new System.NotImplementedException();
        }

        public virtual void AddPhoto()
        {
            throw new System.NotImplementedException();
        }

        public virtual void UpdatePhoto()
        {
            throw new System.NotImplementedException();
        }

        public virtual void DeletePhoto()
        {
            throw new System.NotImplementedException();
        }

    }
}

