//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Photocom.Contracts;
using Photocom.Models.Entities.Database;

namespace Photocom.BusinessLogic.Controllers
{
    public class PhotosProcessor : BaseProcessor
    {

        public PhotosProcessor(IUnitOfWork unitOfWork) : base(unitOfWork)
        {
            
        }

        public int Like(Photo likedPhoto, User user)
        {
            var likedUsers = UnitOfWork.LikeRepository.GetLikesByPhotoId(likedPhoto.Id).Select(x => x.User);

            if (!likedUsers.Contains(user))
            {
                likedPhoto.Likes.Add(new Like() { Photo = likedPhoto, User = user});
            }
            else
            {
                bool removed = UnitOfWork.LikeRepository.RemoveLikeByUserAndPhoto(likedPhoto, user);

                if (removed == false)
                {
                    throw new InvalidOperationException("Error while removing like. Fix please.");
                }
            }

            UnitOfWork.SaveChanges();

            return likedPhoto.Likes.Count;
        }
    }
}

