//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Photocom.BusinessLogic.Controllers
{
    public class PrivilegesProcessor
    {
        public virtual void SetPrivileges()
        {
            throw new System.NotImplementedException();
        }

        public virtual void GetPrivileges()
        {
            throw new System.NotImplementedException();
        }

        public virtual void CheckAccess()
        {
            throw new System.NotImplementedException();
        }

    }

}