//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Photocom.BusinessLogic.Controllers
{
    public class UserProcessor
    {
        public virtual void AddUser()
        {
            throw new System.NotImplementedException();
        }

        public virtual void UpdateUser()
        {
            throw new System.NotImplementedException();
        }

        public virtual void DeleteUser()
        {
            throw new System.NotImplementedException();
        }

        public virtual void GetUsers()
        {
            throw new System.NotImplementedException();
        }

    }

}